type = "javascript"
name = "<< todo >>"

account_id = "<< todo >>"
zone_id = "<< todo >>"
workers_dev = true

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "src"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]
